### ISSUE TITLE
Crea una clase Prueba()

### ISSUE THREAD

**Issue by Cartuchito** [Cartuchito/eclipse#1]
Prueba() con un syso que diga, "Kike Campeón!! "

**Comment by ReginaEscalera** [comment]
donde te mando eso?? dime tu gmail o algo




________________________________
De: Cartuchito <notifications@github.com>
Enviado: miércoles, 26 de septiembre de 2018 13:11
Para: Cartuchito/eclipse
Cc: ReginaEscalera; Assign
Asunto: Re: [Cartuchito/eclipse] Crea una clase Prueba() (#1)


Assigned #1<https://github.com/Cartuchito/eclipse/issues/1> to @ReginaEscalera<https://github.com/ReginaEscalera>.
